In [67]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import roc_curve, auc, roc_auc_score,matthews_corrcoef
from tensorflow.keras.callbacks import Callback,EarlyStopping
import random
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, recall_score, matthews_corrcoef, roc_curve, auc
from tensorflow.keras import backend as K
import itertools
import os
import random
import tensorflow
import tensorflow as tf
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras import utils
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam,SGD
from tensorflow.keras.regularizers import l2
import copy
from sklearn.metrics import roc_auc_score
from Bio import SeqIO
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda, LSTM
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Bidirectional, TimeDistributed
from tensorflow.keras.callbacks import ModelCheckpoint,ReduceLROnPlateau
from numpy import array
from numpy import argmax
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from sklearn.utils import shuffle
from tensorflow.keras import backend as K
from tensorflow.keras.backend import expand_dims
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l1, l2
from sklearn.metrics import roc_curve, auc, classification_report
from tensorflow.keras.models import load_model
import pandas as pd
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D,GlobalMaxPooling1D
from Bio import SeqIO
import random
import functools
import itertools
import os
import random
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape, BatchNormalization
from tensorflow.keras.layers import Conv1D, Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.regularizers import l2
import copy

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
from numpy import sort
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import *
from sklearn.metrics import roc_curve, roc_auc_score, classification_report,auc
import tensorflow.keras
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from tensorflow.keras.layers import Dense, Bidirectional,Dense, LSTM, Activation, Dropout, Flatten, LeakyReLU
from sklearn.metrics import accuracy_score
from tensorflow.keras.regularizers import l2
from tensorflow.keras import regularizers
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import LSTM

from tensorflow.keras.models import Model
from tensorflow.keras.applications import mobilenet_v2, mobilenet, resnet50, densenet
from tensorflow.keras.layers import Dense, MaxPooling2D, Conv2D, Flatten, \
    BatchNormalization, Activation, GlobalAveragePooling2D, DepthwiseConv2D, \
    Dropout, ReLU, Concatenate, Input, add, Conv1D, MaxPooling1D

from tensorflow.keras.layers import LSTM, GRU, SimpleRNN


from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras import backend as K

import matplotlib.pyplot as plt
import math
from tensorflow.keras.callbacks import CSVLogger
from datetime import datetime

import os.path
from scipy.spatial import distance
import scipy.io as sio
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
import os
from sklearn.model_selection import KFold
import numpy as np
import random
from Bio import SeqIO
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Conv1D, MaxPooling1D
from tensorflow.keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l1,l2
from tensorflow.keras import backend as K
from tensorflow.keras.backend import expand_dims
import tensorflow as tf
import pandas as pd
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import tensorflow.keras
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l1,l2
from tensorflow.keras import backend as K
from tensorflow.keras.backend import expand_dims
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
from numpy import sort
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import *
from sklearn.metrics import roc_curve, roc_auc_score, classification_report,auc
import tensorflow.keras
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from tensorflow.keras.layers import Dense, Bidirectional,Dense, LSTM, Activation, Dropout, Flatten, LeakyReLU
from sklearn.metrics import accuracy_score
from tensorflow.keras.regularizers import l2
from tensorflow.keras import regularizers
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import LSTM
from tensorflow.keras.regularizers import l1, l2
from tensorflow.keras import models,layers,optimizers,regularizers
from tensorflow.keras.models import Model
from tensorflow.keras.applications import mobilenet_v2, mobilenet, resnet50, densenet
from tensorflow.keras.layers import Dense, MaxPooling2D, Conv2D, Flatten, \
    BatchNormalization, Activation, GlobalAveragePooling2D, DepthwiseConv2D, \
    Dropout, ReLU, Concatenate, Input, add, Conv1D, MaxPooling1D

from tensorflow.keras.layers import LSTM, GRU, SimpleRNN


from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras import backend as K

import matplotlib.pyplot as plt
import math
from tensorflow.keras.callbacks import CSVLogger
from datetime import datetime

import os.path
from scipy.spatial import distance
import scipy.io as sio

import os 

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import roc_curve, auc, roc_auc_score,matthews_corrcoef
from tensorflow.keras.callbacks import Callback,EarlyStopping
import random
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, recall_score, matthews_corrcoef, roc_curve, auc
from tensorflow.keras import backend as K
import itertools
import os
import random
import tensorflow
import tensorflow as tf
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras import utils
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam,SGD
from tensorflow.keras.regularizers import l2
import copy
from sklearn.metrics import roc_auc_score
from Bio import SeqIO
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda, LSTM
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Bidirectional, TimeDistributed
from tensorflow.keras.callbacks import ModelCheckpoint,ReduceLROnPlateau
from numpy import array
from numpy import argmax
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from sklearn.utils import shuffle
from tensorflow.keras import backend as K
from tensorflow.keras.backend import expand_dims
import matplotlib.pyplot as plt
from tensorflow.keras.regularizers import l1, l2
from sklearn.metrics import roc_curve, auc, classification_report
from tensorflow.keras.models import load_model
import pandas as pd
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling2D,GlobalMaxPooling1D
from Bio import SeqIO
import random
import functools
import itertools
import os
import random
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from tensorflow.keras.layers import Dense, Activation, Flatten, Dropout, Reshape, BatchNormalization
from tensorflow.keras.layers import Conv1D, Conv2D, MaxPooling2D
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import optimizers
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.regularizers import l2
import copy
from sklearn.model_selection import StratifiedKFold

from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score
from tensorflow.keras import models,layers,optimizers,regularizers

In [68]:
import os 
import pickle
os.chdir('/homes/t326h379/CPLM_4_8362')

# Training the Model

In [69]:
import os
from Bio import SeqIO
import numpy as np
import pandas as pd
os.chdir("/homes/t326h379/CPLM_4_8362/")
# Independent Testing
indep_test_x_81 = []
indep_test_y_81 = []
posit_1 = 1;
negat_0 = 0;

aminoacids='ARNDCQEGHILKMFPSTWYVX'

In [70]:
def binary_encode(Sequence_one_hot_encoding): 
    aa2v={x:y for x,y in zip(aminoacids,np.eye(21,21).tolist())}
    aa2v['X']=np.zeros(21)
    encoding=[]
    for i in range(len(Sequence_one_hot_encoding)):
        s=Sequence_one_hot_encoding[i]
        encoding.append([aa2v[x] for x in s])
    encoding=np.array(encoding)
    return encoding

aaindex=pd.read_table('aaindex31.txt',sep='\s+',header=None)
aaindex=aaindex.subtract(aaindex.min(axis=1),axis=0).divide((aaindex.max(axis=1)-aaindex.min(axis=1)),axis=0)
aa=[x for x in 'ARNDCQEGHILKMFPSTWYV']
aaindex=aaindex.to_numpy().T
index={x:y for x,y in zip(aa,aaindex.tolist())}
index['-']=np.zeros(31).tolist()
index['X']=np.zeros(31).tolist()

def index_encode(Sequence_one_hot_encoding):
    encoding=[]
    for i in range(len(Sequence_one_hot_encoding)):
        s=Sequence_one_hot_encoding[i]
        encoding.append([index[x] for x in (s)])
    encoding=np.array(encoding)
    return encoding

alphabet = aminoacids

In [71]:
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

# Test Dataset

In [72]:
def inner1():
    #Input
    data = seq_record.seq

    for char in data:
        if char not in alphabet:
            return
    integer_encoded = [char_to_int[char] for char in data]
    indep_test_x_81.append(integer_encoded)
    indep_test_y_81.append(posit_1)
for seq_record in SeqIO.parse("Independent_Test_Positive_Sites_from_835_proteins.txt", "fasta"):
    inner1()

In [73]:
len(indep_test_x_81)

8226

In [74]:
len(indep_test_y_81)

8226

In [75]:
def inner2():
    #Input
    data = seq_record.seq

    for char in data:
        if char not in alphabet:
            return
    integer_encoded = [char_to_int[char] for char in data]
    indep_test_x_81.append(integer_encoded)
    indep_test_y_81.append(negat_0)
# "Independent_Test_Negative_Sites_from_835_proteins.txt"    
for seq_record in SeqIO.parse("Independent_Test_Negative_Sites_from_773_proteins.txt", "fasta"):
    inner2()

In [76]:
len(indep_test_x_81)

17394

In [77]:
len(indep_test_y_81)

17394

In [78]:
# Changing to array (matrix)    
indep_test_x_81 = np.array(indep_test_x_81)
indep_test_y_81 = np.array(indep_test_y_81)

print(indep_test_x_81.shape,indep_test_y_81.shape)

(17394, 81) (17394,)


In [79]:
indep_test_x_81

array([[11, 11, 14, ...,  2,  0,  8],
       [12, 19,  7, ..., 15,  7, 11],
       [ 8,  6, 17, ...,  6,  6, 19],
       ...,
       [ 9, 18, 10, ..., 11,  6,  0],
       [ 6,  9,  1, ...,  6, 10,  9],
       [ 2, 15,  1, ..., 12,  7,  0]])

In [80]:
indep_test_y_81

array([1, 1, 1, ..., 0, 0, 0])

In [81]:
AAindex_Test_AAAAA_81_Sequence = []
for i in range(len(indep_test_x_81)):
    integer_of_string = str(indep_test_x_81[i])
    integer_of_string = integer_of_string.strip("[").strip("]").strip(" ")
    keras_job = integer_of_string.split()
    individual_AA_peptide = []
    for i in range(len(keras_job)):
        index_value = int(keras_job[i])
        individual_AA_peptide.append(int_to_char.get(index_value))
    individual_AA_peptide = "".join(individual_AA_peptide)
    AAindex_Test_AAAAA_81_Sequence.append(individual_AA_peptide) 

yval = indep_test_y_81

In [82]:
AAindex_Test_AAAAA_81_Sequence

['KKPNYKKLELQVYATFFEIYSGKVFDLLNRKTKLRVLEDGKQQVQVVGLQEREVKCVEDVLKLIDIGNSCRTSGQTSANAH',
 'MVGEDADLPCHLFPTMSAETMELKWVSSSLRQVVNVYADGKEVEDRQSAPYRGRTSILRDGITAGKAALRIHNVTASDSGK',
 'HEWEKHGTCAAQVDALNSQKKYFGRSLELYRELDLNSVLLKLGIKPSINYYQVADFKDALARVYGVIPKIQCLPPSQDEEV',
 'KHGTCAAQVDALNSQKKYFGRSLELYRELDLNSVLLKLGIKPSINYYQVADFKDALARVYGVIPKIQCLPPSQDEEVQTIG',
 'NPDGASHGGPQDSDRHRGDLGNVRADADGRAIFRMEDEQLKVWDVIGRSLIIDEGEDDLGRGGHPLSKITGNSGERLACGI',
 'DGRAIFRMEDEQLKVWDVIGRSLIIDEGEDDLGRGGHPLSKITGNSGERLACGIIARSAGLFQNPKQICSCDGLTIWEERG',
 'DEGEDDLGRGGHPLSKITGNSGERLACGIIARSAGLFQNPKQICSCDGLTIWEERGRPIAGKGRKESAQPPAHLXXXXXXX',
 'VAGVQDVEVHLEDQMVLVHTTLPSQEVQALLEGTGRQAVLKGMGSGQLQNLGAAVAILGGPGTVQGVVRFLQLTPERCLIE',
 'FTRIGRQGDMTDSRTNSFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQEFLLSPTSLGIPNSRLR',
 'FLIAKLQSEPLPFQAPGQVLMEFPKIESVHPQKYAMDVENKIQEKNVEPNISFDGSIQCSGKDAILFKLETAEEIHRKNQQ',
 'FLRGHQETVKDFRLLKNSRLLSWSFDGTVKVWNIITGNKEKDFVCHQGTVLSCDISHDATKFSSTSADKTAKIWSFDLLLP',
 'HIQFTADEKTLISSSDDAEIQVWNWQLDKCIFLRGHQETVKDFRLLKNSRLL

In [83]:
yval

array([1, 1, 1, ..., 0, 0, 0])

In [84]:
len(yval)

17394

In [85]:
x_ind_49 = indep_test_x_81[:,[i for i in range(16,65)]]

In [86]:
x_ind_49.shape

(17394, 49)

In [87]:
x_ind_49

array([[13,  6,  9, ..., 10,  9,  3],
       [15,  0,  6, ..., 16,  0,  7],
       [ 2, 15,  5, ..., 19, 18,  7],
       ...,
       [18,  0, 15, ..., 15,  4, 19],
       [11, 15,  1, ..., 13,  7,  3],
       [16,  5,  3, ..., 10, 11, 11]])

In [88]:
AAindex_indi_AA_Sequence = []
for i in range(len(x_ind_49)):
    integer_of_string = str(x_ind_49[i])
    integer_of_string = integer_of_string.strip("[").strip("]").strip(" ")
    keras_job = integer_of_string.split()
    individual_AA_peptide = []
    for i in range(len(keras_job)):
        index_value = int(keras_job[i])
        individual_AA_peptide.append(int_to_char.get(index_value))
    individual_AA_peptide = "".join(individual_AA_peptide)
    AAindex_indi_AA_Sequence.append(individual_AA_peptide) 

In [89]:
AAindex_indi_AA_Sequence

['FEIYSGKVFDLLNRKTKLRVLEDGKQQVQVVGLQEREVKCVEDVLKLID',
 'SAETMELKWVSSSLRQVVNVYADGKEVEDRQSAPYRGRTSILRDGITAG',
 'NSQKKYFGRSLELYRELDLNSVLLKLGIKPSINYYQVADFKDALARVYG',
 'KYFGRSLELYRELDLNSVLLKLGIKPSINYYQVADFKDALARVYGVIPK',
 'RGDLGNVRADADGRAIFRMEDEQLKVWDVIGRSLIIDEGEDDLGRGGHP',
 'DVIGRSLIIDEGEDDLGRGGHPLSKITGNSGERLACGIIARSAGLFQNP',
 'ITGNSGERLACGIIARSAGLFQNPKQICSCDGLTIWEERGRPIAGKGRK',
 'LVHTTLPSQEVQALLEGTGRQAVLKGMGSGQLQNLGAAVAILGGPGTVQ',
 'SFLHILDILPRLQKLPKYILLENVKGFEVSSTRDLLIQTIENCGFQYQE',
 'GQVLMEFPKIESVHPQKYAMDVENKIQEKNVEPNISFDGSIQCSGKDAI',
 'NSRLLSWSFDGTVKVWNIITGNKEKDFVCHQGTVLSCDISHDATKFSST',
 'DAEIQVWNWQLDKCIFLRGHQETVKDFRLLKNSRLLSWSFDGTVKVWNI',
 'PHTDAVYHACFSEDGQRIASCGADKTLQVFKAETGEKLLEIKAHEDEVL',
 'QEDMEVIVKCCSWSADGARIMVAAKNKIFLFDIHTSGLLGEIHTGHHST',
 'EEEKVRNEPTQQQRAAMLIKMILKKDNDSYVSFYNALLHEGYKDLAALL',
 'YIKWWNVVTGESSQTFYTNGTNLKKIHVSPDFKTYVTVDNLGILYILQT',
 'TSYVRTVLCEGGVPQRPVVFVTRKKLVNAIQQKLSKLKGEPGWVTIHGM',
 'CEGGVPQRPVVFVTRKKLVNAIQQKLSKLKGEPGWVTIHGMAGCGKSVL',
 'YQQAKLQAKQEVDNGMLYLEWINKKN

In [90]:
binaryCoding_Independent_Test = binary_encode(AAindex_indi_AA_Sequence)

In [91]:
binaryCoding_Independent_Test.shape

(17394, 49, 21)

In [92]:
AAindexCoding_Independent_Test = index_encode(AAindex_indi_AA_Sequence)

In [93]:
AAindexCoding_Independent_Test

array([[[0.91520468, 0.90342679, 0.        , ..., 0.83805668,
         0.31841432, 0.89473684],
        [0.26315789, 0.21183801, 0.78      , ..., 0.36842105,
         0.60869565, 0.02631579],
        [0.90935673, 0.78816199, 0.06      , ..., 0.78744939,
         0.52941176, 0.94736842],
        ...,
        [0.9005848 , 0.91277259, 0.18      , ..., 0.81376518,
         1.        , 0.43421053],
        [0.90935673, 0.78816199, 0.06      , ..., 0.78744939,
         0.52941176, 0.94736842],
        [0.37134503, 0.35825545, 0.7       , ..., 0.32995951,
         0.4859335 , 0.15789474]],

       [[0.52339181, 0.3364486 , 0.62      , ..., 0.22672065,
         0.70332481, 0.26315789],
        [0.74853801, 0.56697819, 0.42      , ..., 0.22064777,
         0.85038363, 0.        ],
        [0.26315789, 0.21183801, 0.78      , ..., 0.36842105,
         0.60869565, 0.02631579],
        ...,
        [0.59064327, 0.47975078, 0.58      , ..., 0.35425101,
         0.56649616, 0.22368421],
        [0.7

In [94]:
AAindexCoding_Independent_Test.shape

(17394, 49, 31)

# Training Dataset

In [95]:
train_x_81 = []
train_y_81 = []

def inner1():
    #Input
    data = seq_record.seq

    for char in data:
        if char not in alphabet:
            return
    integer_encoded = [char_to_int[char] for char in data]
    train_x_81.append(integer_encoded)
    train_y_81.append(posit_1)
    
for seq_record in SeqIO.parse("Training_Positive_Sites_from_7507_proteins.txt", "fasta"):
    inner1()

In [96]:
len(train_x_81)

74153

In [97]:

len(train_y_81)

74153

# Rough

In [98]:
pwd

'/homes/t326h379/CPLM_4_8362'

In [99]:
def inner2():
    #Input
    data = seq_record.seq

    for char in data:
        if char not in alphabet:
            return
    integer_encoded = [char_to_int[char] for char in data]
    train_x_81.append(integer_encoded)
    train_y_81.append(negat_0)
for seq_record in SeqIO.parse("Training_Negative_Sites_from_7507_proteins.txt", "fasta"):
    inner2()

In [100]:
len(train_x_81)

145512

In [101]:
len(train_y_81)

145512

In [102]:
# Changing to array (matrix)    
train_x_81 = np.array(train_x_81)
train_y_81 = np.array(train_y_81)

print(train_x_81.shape,train_y_81.shape)

(145512, 81) (145512,)


In [103]:
train_x_81

array([[19, 14,  0, ..., 10,  0, 13],
       [15, 13, 10, ...,  6, 18, 18],
       [13,  9, 13, ...,  3,  1, 19],
       ...,
       [13, 14,  9, ..., 15, 13,  6],
       [ 9, 10,  8, ...,  7,  2,  5],
       [ 1,  5, 10, ..., 15,  6,  9]])

In [104]:
train_y_81

array([1, 1, 1, ..., 0, 0, 0])

In [105]:
AAindex_Training_AAAAA_81_Sequence = []
for i in range(len(train_x_81)):
    integer_of_string = str(train_x_81[i])
    integer_of_string = integer_of_string.strip("[").strip("]").strip(" ")
    keras_job = integer_of_string.split()
    individual_AA_peptide = []
    for i in range(len(keras_job)):
        index_value = int(keras_job[i])
        individual_AA_peptide.append(int_to_char.get(index_value))
    individual_AA_peptide = "".join(individual_AA_peptide)
    AAindex_Training_AAAAA_81_Sequence.append(individual_AA_peptide) 

ytrain = train_y_81

In [106]:
len(AAindex_Training_AAAAA_81_Sequence)

145512

In [107]:
len(ytrain)

145512

In [108]:
x_train_49 = train_x_81[:,[i for i in range(16,65)]]

In [109]:
x_train_49.shape

(145512, 49)

In [110]:
EmbeddingCoding_Training = x_train_49

In [111]:
AAindex_training_AA_Sequence = []
for i in range(len(x_train_49)):
    integer_of_string = str(x_train_49[i])
    integer_of_string = integer_of_string.strip("[").strip("]").strip(" ")
    keras_job = integer_of_string.split()
    individual_AA_peptide = []
    for i in range(len(keras_job)):
        index_value = int(keras_job[i])
        individual_AA_peptide.append(int_to_char.get(index_value))
    individual_AA_peptide = "".join(individual_AA_peptide)
    AAindex_training_AA_Sequence.append(individual_AA_peptide) 

In [112]:
len(AAindex_training_AA_Sequence[0])

49

In [113]:
AAindex_training_AA_Sequence

['DWFVVYKLPALRGSGEAAQRGLQYKYLDESSGGWRDGRALINSPEGAVG',
 'FDPNQLSVATLLFEGDREKVLQHEKQVYDIAAKFGGLAAGEDNGQRGYL',
 'PLSGMGLPTFKEWIQNTLGVNVEHKTTSKASLNPSDTPPSVVNEDFLHD',
 'VGKLRKQWLKESISDVGFGMLKSVKEYVDPNNIFGNRNLLXXXXXXXXX',
 'HHGVGKLRKQWLKESISDVGFGMLKSVKEYVDPNNIFGNRNLLXXXXXX',
 'IPKKRQEVMKWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLPTFKEW',
 'ITKFKGFDPNQLSVATLLFEGDREKVLQHEKQVYDIAAKFGGLAAGEDN',
 'TSKASLNPSDTPPSVVNEDFLHDLKETNISYSQEADDRVFRAHGHCLHE',
 'GHEPDSLEFSTVGGWVSTRASGMKKNIYGNIEDLVVHIKMVTPRGIIEK',
 'MGSEGTLGVITEATIKIRPVPEYQKYGSVAFPNFEQGVACLREIAKQRC',
 'KWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLPTFKEWIQNTLGVNV',
 'MGLPTFKEWIQNTLGVNVEHKTTSKASLNPSDTPPSVVNEDFLHDLKET',
 'HALKPQVSSIFTSFLDGLKKFYITKFKGFDPNQLSVATLLFEGDREKVL',
 'ATLLFEGDREKVLQHEKQVYDIAAKFGGLAAGEDNGQRGYLLTYVIAYI',
 'QESGTIPKKRQEVMKWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLP',
 'PKKRQEVMKWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLPTFKEWI',
 'LKPQVSSIFTSFLDGLKKFYITKFKGFDPNQLSVATLLFEGDREKVLQH',
 'KNIYGNIEDLVVHIKMVTPRGIIEKSCQGPRMSTGPDIHHFIMGSEGTL',
 'RRAASAATAAPTATPAAQESGTIPKK

In [114]:
len(AAindex_training_AA_Sequence)

145512

In [115]:
AAindex_training_AA_Sequence

['DWFVVYKLPALRGSGEAAQRGLQYKYLDESSGGWRDGRALINSPEGAVG',
 'FDPNQLSVATLLFEGDREKVLQHEKQVYDIAAKFGGLAAGEDNGQRGYL',
 'PLSGMGLPTFKEWIQNTLGVNVEHKTTSKASLNPSDTPPSVVNEDFLHD',
 'VGKLRKQWLKESISDVGFGMLKSVKEYVDPNNIFGNRNLLXXXXXXXXX',
 'HHGVGKLRKQWLKESISDVGFGMLKSVKEYVDPNNIFGNRNLLXXXXXX',
 'IPKKRQEVMKWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLPTFKEW',
 'ITKFKGFDPNQLSVATLLFEGDREKVLQHEKQVYDIAAKFGGLAAGEDN',
 'TSKASLNPSDTPPSVVNEDFLHDLKETNISYSQEADDRVFRAHGHCLHE',
 'GHEPDSLEFSTVGGWVSTRASGMKKNIYGNIEDLVVHIKMVTPRGIIEK',
 'MGSEGTLGVITEATIKIRPVPEYQKYGSVAFPNFEQGVACLREIAKQRC',
 'KWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLPTFKEWIQNTLGVNV',
 'MGLPTFKEWIQNTLGVNVEHKTTSKASLNPSDTPPSVVNEDFLHDLKET',
 'HALKPQVSSIFTSFLDGLKKFYITKFKGFDPNQLSVATLLFEGDREKVL',
 'ATLLFEGDREKVLQHEKQVYDIAAKFGGLAAGEDNGQRGYLLTYVIAYI',
 'QESGTIPKKRQEVMKWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLP',
 'PKKRQEVMKWNGWGYNDSKFIFNKKGQIELTGKRYPLSGMGLPTFKEWI',
 'LKPQVSSIFTSFLDGLKKFYITKFKGFDPNQLSVATLLFEGDREKVLQH',
 'KNIYGNIEDLVVHIKMVTPRGIIEKSCQGPRMSTGPDIHHFIMGSEGTL',
 'RRAASAATAAPTATPAAQESGTIPKK

In [116]:
ytrain

array([1, 1, 1, ..., 0, 0, 0])

In [117]:
binaryCoding_Training = binary_encode(AAindex_training_AA_Sequence)

In [118]:
binaryCoding_Training.shape

(145512, 49, 21)

In [119]:
AAindexCoding_Training = index_encode(AAindex_training_AA_Sequence)

In [120]:
AAindexCoding_Training.shape

(145512, 49, 31)

In [121]:
# AAindex Model
X_input_AAindex = tf.keras.Input(shape=(49,31))
AAindex_output_1 = layers.LSTM(64,return_sequences=True,input_shape=(49,31))(X_input_AAindex)
AAindex_output_2 = layers.Dropout(0.3)(AAindex_output_1)
AAindex_output_3 = layers.Flatten()(AAindex_output_2)
AAindex_output_4 = layers.Dense(32,activation='relu',kernel_regularizer=regularizers.l1(1e-4))(AAindex_output_3)
AAindex_output_5 = layers.Dropout(0.3)(AAindex_output_4)
AAindex_output_6_final = layers.Dense(2,activation='softmax',kernel_regularizer=regularizers.l1(1e-4))(AAindex_output_5)

# One Hot Encoding Model
X_input_21_One_HOT = tf.keras.Input(shape=(49,21))
One_HOT_CONV_1D_1 = tf.keras.layers.Conv1D(16,3,activation='relu',kernel_regularizer=regularizers.l1(1e-4),input_shape=(49,21),padding='same')(X_input_21_One_HOT)
One_HOT_CONV_1D_2 = tf.keras.layers.MaxPooling1D(2)(One_HOT_CONV_1D_1)
One_HOT_CONV_1D_3 = tf.keras.layers.Flatten()(One_HOT_CONV_1D_2)
One_HOT_CONV_1D_4 = tf.keras.layers.Dense(512,activation='relu',kernel_regularizer=regularizers.l1(1e-4))(One_HOT_CONV_1D_3)
One_HOT_CONV_1D_5 = tf.keras.layers.Dropout(0.5)(One_HOT_CONV_1D_4)
One_HOT_CONV_1D_output_6 = tf.keras.layers.Dense(2,activation='softmax',kernel_regularizer=regularizers.l1(1e-4))(One_HOT_CONV_1D_5)

#Embedding Model
X_input_Emb = tf.keras.Input(shape=(49,))
emb_output = tf.keras.layers.Embedding(23, 21, input_length=21)(X_input_Emb)
Conv1D_output = tf.keras.layers.Conv1D(256, kernel_size = 3,activation='relu',kernel_initializer='he_normal')(emb_output)
Maxpool_output = tf.keras.layers.MaxPooling1D(2)(Conv1D_output)
Dropout_layer = tf.keras.layers.Dropout(0.4)(Maxpool_output)

Conv1D_1_output = tf.keras.layers.Conv1D(256,7,activation='relu',kernel_initializer='he_normal')(Dropout_layer)
Conv1D_1_output_1 = tf.keras.layers.MaxPooling1D(2)(Conv1D_1_output)
Conv1D_1_output_2 = tf.keras.layers.Dropout(0.4)(Conv1D_1_output_1)

Flatten_layer_output = tf.keras.layers.Flatten()(Conv1D_1_output_2)
Flatten_layer_output_1 = tf.keras.layers.Dense(768,activation='relu',kernel_initializer='he_normal')(Flatten_layer_output)
Flatten_layer_output_2 = tf.keras.layers.Dropout(0.5)(Flatten_layer_output_1)
Flatten_layer_output_3 = tf.keras.layers.Dense(256,activation='relu',kernel_initializer='he_normal')(Flatten_layer_output_2)
Flatten_layer_output_4 = tf.keras.layers.Dropout(0.5)(Flatten_layer_output_3)
Embedding_output_final_5 = tf.keras.layers.Dense(2,activation='softmax')(Flatten_layer_output_4)


XX = tf.keras.layers.Concatenate()([AAindex_output_6_final, One_HOT_CONV_1D_output_6, Embedding_output_final_5])

out = Dense(6)(XX)
out_1 = Activation('relu')(out)

out_2 = Dense(2)(out_1)
out_Final = Activation('softmax')(out_2)

model = Model(inputs=[X_input_AAindex, X_input_21_One_HOT, X_input_Emb], outputs=[out_Final])

In [122]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_6 (InputLayer)           [(None, 49)]         0           []                               
                                                                                                  
 embedding_1 (Embedding)        (None, 49, 21)       483         ['input_6[0][0]']                
                                                                                                  
 conv1d_4 (Conv1D)              (None, 47, 256)      16384       ['embedding_1[0][0]']            
                                                                                                  
 max_pooling1d_4 (MaxPooling1D)  (None, 23, 256)     0           ['conv1d_4[0][0]']               
                                                                                            

In [123]:
Y_train = tf.keras.utils.to_categorical(ytrain,2)

In [124]:
Y_train.shape

(145512, 2)

In [125]:
optimize_2 = tf.keras.optimizers.Adam(learning_rate =0.001)
optimize_3 = tf.keras.optimizers.Nadam()
optimize_4 = tf.keras.optimizers.SGD()
optimize_5 = tf.keras.optimizers.RMSprop()
optimize_6 = tf.keras.optimizers.Adagrad()
loss_1 = tf.keras.losses.categorical_crossentropy
loss_2 = tf.keras.losses.binary_crossentropy

model.compile(loss=loss_2,
            optimizer=optimize_2,
            metrics=['accuracy'])

history = model.fit([AAindexCoding_Training, binaryCoding_Training, EmbeddingCoding_Training], Y_train, batch_size=32, epochs=15, verbose=1)

Epoch 1/15
4548/4548 [==============================] - 80s 16ms/step - loss: 0.3965 - accuracy: 0.8470
Epoch 2/15
4548/4548 [==============================] - 75s 17ms/step - loss: 0.3339 - accuracy: 0.8673
Epoch 3/15
4548/4548 [==============================] - 75s 17ms/step - loss: 0.3272 - accuracy: 0.8680
Epoch 4/15
4548/4548 [==============================] - 75s 16ms/step - loss: 0.3255 - accuracy: 0.8683
Epoch 5/15
4548/4548 [==============================] - 76s 17ms/step - loss: 0.3239 - accuracy: 0.8685
Epoch 6/15
4548/4548 [==============================] - 75s 17ms/step - loss: 0.3216 - accuracy: 0.8684
Epoch 7/15
4548/4548 [==============================] - 76s 17ms/step - loss: 0.3202 - accuracy: 0.8685
Epoch 8/15
4548/4548 [==============================] - 76s 17ms/step - loss: 0.3189 - accuracy: 0.8687
Epoch 9/15
4548/4548 [==============================] - 75s 17ms/step - loss: 0.3193 - accuracy: 0.8689
Epoch 10/15
4548/4548 [==============================] - 76s 17m

In [126]:
EmbeddingCoding_X_Test = x_ind_49
binaryCoding_X_Test = binaryCoding_Independent_Test
AA_Index_X_Test = AAindexCoding_Independent_Test

In [127]:
y_independent = yval

In [128]:
binaryCoding_X_Test.shape

(17394, 49, 21)

In [129]:
AA_Index_X_Test.shape

(17394, 49, 31)

In [130]:
EmbeddingCoding_X_Test.shape

(17394, 49)

In [131]:
X_independent = [AA_Index_X_Test, binaryCoding_X_Test, EmbeddingCoding_X_Test]
Y_pred = model.predict(X_independent)
Y_pred = (Y_pred > 0.5)
y_pred = [np.argmax(y, axis=None, out=None) for y in Y_pred]
y_pred = np.array(y_pred)

confusion = confusion_matrix(y_independent,y_pred)

print("Matthews Correlation : ",matthews_corrcoef(y_independent, y_pred))
print("Confusion Matrix : \n",confusion_matrix(y_independent, y_pred))
print("Accuracy on test set:   ",accuracy_score(y_independent, y_pred))

cm = confusion_matrix(y_independent, y_pred)

TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]

mcc = matthews_corrcoef(y_independent, y_pred)

Sensitivity = TP/(TP+FN)

Specificity = TN/(TN+FP)

print("Sensitivity:   ",Sensitivity,"\t","Specificity:   ",Specificity)

print(classification_report(y_independent, y_pred))

fpr, tpr, _ = roc_curve(y_independent, y_pred)

roc_auc_test = auc(fpr,tpr)

print("Area Under Curve:   ",roc_auc_test)

544/544 [==============================] - 3s 5ms/step
Matthews Correlation :  0.6168266760541969
Confusion Matrix : 
 [[7825 1343]
 [1981 6245]]
Accuracy on test set:    0.8088996205588134
Sensitivity:    0.7591782154145392 	 Specificity:    0.8535122164048866
              precision    recall  f1-score   support

           0       0.80      0.85      0.82      9168
           1       0.82      0.76      0.79      8226

    accuracy                           0.81     17394
   macro avg       0.81      0.81      0.81     17394
weighted avg       0.81      0.81      0.81     17394

Area Under Curve:    0.8063452159097129


In [132]:
model.save("Final_CPLM_4_Human_Dataset_MMUbiPred_Model_trained_for_15_epochs.h5")

# Thank You.